name: Sync repository settings
on:
  workflow_dispatch:

jobs:
  sync-general-settings:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - repository: "phkiener/Swallow.Validation"
          - repository: "phkiener/Swallow.Refactor"
          - repository: "phkiener/Swallow.ChainOfInjection"
          - repository: "phkiener/Swallow.Console"
          - repository: "phkiener/Swallow.TaskRunner"
          - repository: "phkiener/Swallow.Flux"
          - repository: "phkiener/Swallow.ContentSecurityPolicy"
          - repository: "phkiener/Swallow.MSBuild.Node"
    steps:
      - name: Generate GH token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          client-id: ${{ vars.SYNC_APP_CLIENT_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ matrix.repository }}

      - name: Set general settings
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh repo edit ${{ matrix.repository }} \
            --enable-discussions=false \
            --enable-issues \
            --enable-projects=false \
            --enable-wiki=false \
            --enable-rebase-merge=false \
            --enable-merge-commit=false \
            --enable-auto-merge=false \
            --enable-squash-merge \
            --squash-merge-commit-message pr-title-description \
            --delete-branch-on-merge

      - name: Set secret for NuGet publish
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
            gh secret set NUGET_USER --body ${{ secrets.NUGET_USER }} --repo ${{ matrix.repository }}

      - name: Set actions settings
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
            gh api \
              --method PUT \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              /repos/${{ matrix.repository }}/actions/permissions/artifact-and-log-retention \
              -F "days=7"

            gh api \
              --method PUT \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              /repos/${{ matrix.repository }}/actions/permissions/fork-pr-contributor-approval \
              -f 'approval_policy=all_external_contributors'

            gh api \
              --method PUT \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              /repos/${{ matrix.repository }}/actions/permissions/selected-actions \
              --input - <<< '{
              "github_owned_allowed": true,
              "verified_allowed": false,
              "patterns_allowed": [
                "NuGet/*",
              ]
            }'
