name: Sync general settings
on:
  workflow_dispatch:
jobs:
  sync-general-settings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repository: "phkiener/Swallow.Validation"
          #- repository: "phkiener/Swallow.Refactor"
          #- repository: "phkiener/Swallow.ChainOfInjection"
          #- repository: "phkiener/Swallow.Console"
          #- repository: "phkiener/Swallow.TaskRunner"
          #- repository: "phkiener/Swallow.Flux"
          #- repository: "phkiener/Swallow.ContentSecurityPolicy"
          #- repository: "phkiener/Swallow.MSBuild.Node"
    steps:
      - name: Generate GH token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          client-id: ${{ vars.SYNC_APP_CLIENT_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Apply settings to repository
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh repo edit ${{ matrix.repository }} \
            --enable-discussions=false \
            --enable-issues \
            --enable-projects=false \
            --enable-wiki=false \
            --enable-rebase-merge=false \
            --enable-merge-commit=false \
            --enable-auto-merge=false \
            --enable-squash-merge \
            --squash-merge-commit-message pr-title-description \
            --delete-branch-on-merge
